Zizzamia/perfume.js

src/perfume.ts
Small fixes to logging to make it more coherent. Fixes #1
=> Improved logging

__tests__/perfume.spec.ts, package-lock.json, package.json, src/perfume.ts, tsling.json, tslint.json
- Remove `prettier` since it's difficult to work with in the current workflow (triggers on commit then tslint fails, etc) and rely solely on pure tslint
- Fix `tsling.json` to `tslint.json`
- Fix all linting errors
- `npm run lint`
- `npm run test`
=> build(lint): Remove prettier, adjust tslint, fix linting errors

__tests__/perfume.spec.ts, docs/src/app/app.component.html, docs/src/app/app.component.ts, src/emulated-performance.ts, src/performance-impl.ts, src/performance.ts, src/perfume.ts
Example:
```js
const instance = new Perfume({timeToInteractive: true});
instance.waitUntilTimeToInteractive().then((time) => {
console.log(`${time}ms`)
});
```
=> feat: timeToInteractive as promise

README.md
- fixed the UMD path
- the `timeToInteractive` option isn't available anymore
=> Fix some errors

README-ZH.md, README-zh_CN.md, README.md
Add Chinese instructions to facilitate recommendation to colleagues.
=> docs: New Chinese Readme

README.md
I've added a new section "plugins" linking the plugin of mine 😊
=> Add the plugin for Gatsby JS

README.md
Used across multiple properties, and internal apps too 👍
=> Added Hearst to list of companies

README.md
Thanks again for the amazing lib @Zizzamia! ❤️
I added some links to the docs.
Other relevant links for folks curious on how this analytics plugin works:
- NPM package: https://www.npmjs.com/package/@analytics/perfumejs
- Source code: https://github.com/DavidWells/analytics/tree/master/packages/analytics-plugin-perfumejs
- Docs link: https://getanalytics.io/plugins/perfumejs/
- Example: https://analytics-perfumejs-example.netlify.app/
- Example code: https://github.com/DavidWells/analytics/tree/master/examples/using-perfumejs
- Video: https://www.youtube.com/watch?v=9DZAVpAubtQ
=> Add analytics example to docs

README.md, __tests__/observe.spec.ts, __tests__/perfume.spec.ts, docs/src/app/perfume.ts, rollup.config.ts, src/config.ts, src/observe.ts, src/perfume.ts, src/types.ts
As requested: https://github.com/Zizzamia/perfume.js/pull/124#discussion_r433385898
=> feat: Add option to enable element timing

__tests__/perfume.spec.ts, src/perfume.ts
=> fix: to not call storage.estimate if it's not supported

README-it.md, README-zh_CN.md, README.md, package-lock.json, package.json
=> chore: Italian README

README-zh_CN.md
Adapted to the latest version of Chinese documents
=> fix: Chinese README

README-it.md, README-zh_CN.md, README.md
=> fix: tbt5S => tbt10S

src/isLowEnd.ts
converted to switch eliminated some code paths and removed dependency on includes
closes:
https://github.com/Zizzamia/perfume.js/issues/148
=> Update isLowEnd.ts to support ie11

README-it.md, README-ko.md, README-zh_CN.md, docs/src/index.html
Changed default value of maxMeasureTime in according to value from config
=> changed default value of maxMeasureTime in according to config

__tests__/userJourney/measureUserJourney.spec.ts, __tests__/userJourney/measureUserJourneyStep.ts, src/userJourney/getJourneyMetricName.ts, src/userJourney/getJourneyStepMetricName.ts, src/userJourney/getJourneyStepVitalMetricName.ts, src/userJourney/getRating.ts, src/userJourney/measureJourney.ts, src/userJourney/measureJourneyStep.ts, src/userJourney/measureJourneySteps.ts, src/userJourney/userJourneyConstants.ts
Final Part of User Journey feature addition. 
Added ability to measure User Journeys and steps 
** Still need to fix one of the tests
=> Measuring User Journeys and Steps

__tests__/steps/measureStep.spec.ts, __tests__/steps/onMarkJourney.spec.ts, __tests__/stepsTestConstants.ts, src/steps/measureStep.ts, src/steps/measureSteps.ts
=> Adjusted tests

src/perfume.ts
Exported Mark step functions from perfume
=> Exported mark step functions

README.md, __tests__/perfume.spec.ts, __tests__/steps/markJourney.spec.ts, __tests__/steps/markJourneyOnce.spec.ts, __tests__/steps/measureStep.spec.ts, __tests__/steps/navSteps.spec.ts, __tests__/steps/onMarkJourney.spec.ts, __tests__/steps/setStepsMap.spec.ts, __tests__/stepsTestConstants.ts, src/config.ts, src/perfume.ts, src/steps/measureStep.ts, src/steps/measureSteps.ts, src/steps/navigationSteps.ts, src/steps/setStepsMap.ts, src/steps/steps.ts, src/types.ts
Added new feature to only track active steps, will no longer allow 'stale' steps to be considered after after 2 navigation changes. 
Added docs on Steps
=> Added feature to only track active steps

__tests__/initPerfume.spec.ts, __tests__/log.spec.ts, __tests__/markNTBT.spec.ts, __tests__/steps/measureStep.spec.ts, __tests__/steps/onMarkJourney.spec.ts, __tests__/stepsTestConstants.ts, __tests__/vitalsScore.spec.ts, src/isLowEnd.ts, src/vitalsScore.ts
This PR fixes broken tests and adds additional tests to increase coverage
=> Increase Test Coverage

src/perfume.ts
=> Added markNTBT to export list 

CHANGELOG.md, README.md, package.json, src/initPerfume.ts
* **feat** added export for `markNTBT` function.
=> chore: release v9.2.0 ⚡
